# -*- coding: utf-8 -*-
"""Question 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CpE6keY5Tq9tkk8Sygkd01azFXKzbYrn
"""

!pip install --upgrade wandb
import wandb
!wandb login 3c967c63b099a3b2acd600aa30008e7de1ea6498

from wandb.keras import WandbCallback
from keras.datasets import fashion_mnist
from matplotlib import pyplot as plt
(train_X,train_Y),(test_X,test_Y)=fashion_mnist.load_data()

wandb.init(project='fashion_mnist',entity='adi00510')
classes=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']
images=[]
labels=[]
for i in range(len(train_X)):
  if(len(labels)==10):
    break
  if(classes[train_Y[i]] not in labels):
    images.append(train_X[i])
    labels.append(classes[train_Y[i]])

wandb.log({"Question 1": [wandb.Image(img, caption=lbl) for img,lbl in zip(images,labels)]})
